# Generated by Django 2.2.5 on 2019-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(max_length=4, verbose_name='Status')),
                ('palyer1_name', models.CharField(max_length=50, verbose_name='Player 1 Name')),
                ('player2_name', models.CharField(max_length=50, verbose_name='Player 2 Name')),
                ('player1_id', models.CharField(blank=True, max_length=16, verbose_name='Player 1 ID')),
                ('player2_id', models.CharField(blank=True, max_length=16, verbose_name='Player 2 ID')),
                ('runs', models.TextField(blank=True, verbose_name='Innings')),
                ('seconds', models.TextField(blank=True, verbose_name='Seconds')),
                ('active_run', models.IntegerField(max_length=11, verbose_name='Active Run')),
                ('allow_draw', models.SmallIntegerField(verbose_name='Allow Drawn')),
                ('last_shoot', models.SmallIntegerField(max_length=1, verbose_name='Last Shoot')),
                ('score_limit', models.SmallIntegerField(max_length=4, verbose_name='Score Limit')),
                ('inning_limit', models.SmallIntegerField(max_length=4, verbose_name='Inning Limit')),
                ('timeout_limit', models.SmallIntegerField(max_length=4, verbose_name='Timeout Limit')),
                ('player1_timeout', models.SmallIntegerField(max_length=4, verbose_name='Player 1 Timeout')),
                ('player2_timeout', models.SmallIntegerField(max_length=4, verbose_name='Player 2 Timeout')),
                ('player1_timeavg', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Player 1 Timeavg')),
                ('player2_timeavg', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Player 2 Timeavg')),
                ('positions_switched', models.SmallIntegerField(max_length=1, verbose_name='Positions Switched')),
                ('color_switched', models.SmallIntegerField(max_length=1, verbose_name='Color Switched')),
                ('theme_color', models.CharField(max_length=12, verbose_name='Theme Color')),
                ('time_force', models.SmallIntegerField(max_length=1, verbose_name='Time Force')),
                ('tour_name', models.CharField(blank=True, max_length=100, verbose_name='Tour Name')),
                ('group_name', models.CharField(blank=True, max_length=100, verbose_name='Group Name')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
